# Generated by Django 3.0.8 on 2020-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_auto_20200711_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ipaddress',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='ipaddress',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
