# Generated by Django 3.0.8 on 2020-07-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_auto_20200711_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messages',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.Room'),
        ),
    ]
